[tools]
bun            = "1.2.14"
cargo-binstall = "1.12.0"
cosign         = "2.5.0"
go             = "1.24.3"
node           = "22.14.0"
rust           = "1.86.0"
slsa-verifier  = "2.7.0"
uv             = "0.6.17"

[settings.npm]
bun = true
[settings.pipx]
uvx = true
