[tools]
cargo-binstall = "1.12.0"
cosign         = "2.5.3"
go             = "1.24.7"
node           = "22.18.0"
rust           = "1.88.0"
slsa-verifier  = "2.7.0"

[settings.npm]
bun = true
[settings.pipx]
uvx = true
