[tools]
bun            = "1.2.19"
cargo-binstall = "1.12.0"
cosign         = "2.5.3"
go             = "1.24.6"
node           = "22.17.1"
rust           = "1.88.0"
slsa-verifier  = "2.7.0"
uv             = "0.8.13"

[settings.npm]
bun = true
[settings.pipx]
uvx = true
