#!/usr/bin/env bash
#MISE description="Load secrets from file"
#USAGE arg "<file>" help="The file containing secrets (e.g ~/.env.secrets)"
set -euo pipefail

if [[ -f "$usage_file" ]]; then
  set -o allexport
  source "$usage_file"
  set +o allexport
else
  echo "$usage_file does not exist!"
  exit 1
fi
